// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wordman/wordman.proto

/*
Package wordman is a generated protocol buffer package.

It is generated from these files:
	wordman/wordman.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	GetPictureListReq
	GetPictureListResp
	Picture
*/
package wordman

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	// common.Result result = 1;
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPictureListReq struct {
	Page  int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetPictureListReq) Reset()                    { *m = GetPictureListReq{} }
func (m *GetPictureListReq) String() string            { return proto.CompactTextString(m) }
func (*GetPictureListReq) ProtoMessage()               {}
func (*GetPictureListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPictureListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPictureListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetPictureListResp struct {
	StatusCode int32      `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	Data       []*Picture `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	ErrMsg     string     `protobuf:"bytes,3,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *GetPictureListResp) Reset()                    { *m = GetPictureListResp{} }
func (m *GetPictureListResp) String() string            { return proto.CompactTextString(m) }
func (*GetPictureListResp) ProtoMessage()               {}
func (*GetPictureListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPictureListResp) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetPictureListResp) GetData() []*Picture {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPictureListResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type Picture struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ImgNum int32  `protobuf:"varint,4,opt,name=imgNum" json:"imgNum,omitempty"`
	ImgSrc string `protobuf:"bytes,5,opt,name=imgSrc" json:"imgSrc,omitempty"`
}

func (m *Picture) Reset()                    { *m = Picture{} }
func (m *Picture) String() string            { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()               {}
func (*Picture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Picture) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Picture) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Picture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Picture) GetImgNum() int32 {
	if m != nil {
		return m.ImgNum
	}
	return 0
}

func (m *Picture) GetImgSrc() string {
	if m != nil {
		return m.ImgSrc
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "wordman.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "wordman.HelloReply")
	proto.RegisterType((*GetPictureListReq)(nil), "wordman.GetPictureListReq")
	proto.RegisterType((*GetPictureListResp)(nil), "wordman.GetPictureListResp")
	proto.RegisterType((*Picture)(nil), "wordman.Picture")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Wordman service

type WordmanClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetPictureList(ctx context.Context, in *GetPictureListReq, opts ...grpc.CallOption) (*GetPictureListResp, error)
}

type wordmanClient struct {
	cc *grpc.ClientConn
}

func NewWordmanClient(cc *grpc.ClientConn) WordmanClient {
	return &wordmanClient{cc}
}

func (c *wordmanClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/wordman.Wordman/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordmanClient) GetPictureList(ctx context.Context, in *GetPictureListReq, opts ...grpc.CallOption) (*GetPictureListResp, error) {
	out := new(GetPictureListResp)
	err := grpc.Invoke(ctx, "/wordman.Wordman/GetPictureList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wordman service

type WordmanServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetPictureList(context.Context, *GetPictureListReq) (*GetPictureListResp, error)
}

func RegisterWordmanServer(s *grpc.Server, srv WordmanServer) {
	s.RegisterService(&_Wordman_serviceDesc, srv)
}

func _Wordman_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordmanServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordman.Wordman/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordmanServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wordman_GetPictureList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPictureListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordmanServer).GetPictureList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordman.Wordman/GetPictureList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordmanServer).GetPictureList(ctx, req.(*GetPictureListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wordman_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wordman.Wordman",
	HandlerType: (*WordmanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Wordman_SayHello_Handler,
		},
		{
			MethodName: "GetPictureList",
			Handler:    _Wordman_GetPictureList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wordman/wordman.proto",
}

func init() { proto.RegisterFile("wordman/wordman.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xa5, 0x69, 0xd3, 0xe8, 0x28, 0x45, 0x47, 0x2b, 0x4b, 0x04, 0x29, 0x8b, 0x48, 0x4f, 0x15,
	0x2a, 0x78, 0xf3, 0xe4, 0x41, 0x05, 0x15, 0xd9, 0x1e, 0x3c, 0xaf, 0xcd, 0x12, 0x16, 0xb2, 0x4d,
	0xba, 0xbb, 0x41, 0xfa, 0x0f, 0x7e, 0xb4, 0xec, 0x66, 0x13, 0x6b, 0xc5, 0x53, 0xe6, 0xcd, 0xbc,
	0xbc, 0xbc, 0x79, 0x13, 0x18, 0x7f, 0x96, 0x3a, 0x53, 0x7c, 0x75, 0x1d, 0x9e, 0xb3, 0x4a, 0x97,
	0xb6, 0xc4, 0x24, 0x40, 0x4a, 0xe1, 0xf0, 0x51, 0x14, 0x45, 0xc9, 0xc4, 0xba, 0x16, 0xc6, 0x22,
	0xc2, 0x60, 0xc5, 0x95, 0x20, 0xbd, 0x49, 0x6f, 0xba, 0xcf, 0x7c, 0x4d, 0xaf, 0x00, 0x02, 0xa7,
	0x2a, 0x36, 0x48, 0x20, 0x51, 0xc2, 0x18, 0x9e, 0x0b, 0x12, 0x79, 0x52, 0x0b, 0xe9, 0x1d, 0x1c,
	0x3f, 0x08, 0xfb, 0x26, 0x97, 0xb6, 0xd6, 0xe2, 0x59, 0x1a, 0xcb, 0xc4, 0xda, 0x09, 0x56, 0x8e,
	0xeb, 0x04, 0x63, 0xe6, 0x6b, 0x3c, 0x85, 0xb8, 0x90, 0x4a, 0x5a, 0x2f, 0x10, 0xb3, 0x06, 0x50,
	0x0d, 0xb8, 0xfb, 0xba, 0xa9, 0xf0, 0x02, 0xc0, 0x58, 0x6e, 0x6b, 0x73, 0x5f, 0x66, 0xad, 0xca,
	0x56, 0x07, 0x2f, 0x61, 0x90, 0x71, 0xcb, 0x49, 0x34, 0xe9, 0x4f, 0x0f, 0xe6, 0x47, 0xb3, 0x76,
	0xcf, 0xa0, 0xc3, 0xfc, 0x14, 0xcf, 0x60, 0x28, 0xb4, 0x7e, 0x31, 0x39, 0xe9, 0x7b, 0xcf, 0x01,
	0x51, 0x03, 0x49, 0x20, 0xe2, 0x08, 0x22, 0x99, 0x85, 0xbd, 0x23, 0x99, 0x39, 0x93, 0x56, 0xda,
	0xa2, 0xdd, 0xb2, 0x01, 0x5d, 0x3e, 0xfd, 0x9f, 0x7c, 0x9c, 0xb8, 0x54, 0xf9, 0x6b, 0xad, 0xc8,
	0xc0, 0xdb, 0x0b, 0x28, 0xf4, 0x17, 0x7a, 0x49, 0xe2, 0xe6, 0xa3, 0x0d, 0x9a, 0x7f, 0xf5, 0x20,
	0x79, 0x6f, 0x6c, 0xe2, 0x2d, 0xec, 0x2d, 0xf8, 0xc6, 0xc7, 0x8b, 0xe3, 0xce, 0xfc, 0xf6, 0x49,
	0xd2, 0x93, 0xdd, 0xb6, 0xbb, 0xc2, 0x13, 0x8c, 0x7e, 0x87, 0x85, 0x69, 0x47, 0xfb, 0x73, 0x84,
	0xf4, 0xfc, 0xdf, 0x99, 0xa9, 0x3e, 0x86, 0xfe, 0x97, 0xb8, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x6c, 0xd2, 0xc1, 0x00, 0x2b, 0x02, 0x00, 0x00,
}
